# 本文件用于把用户的个人信息存档入一个JSON文件供查询
import json

# 这是一个包含用户数据的字典
users_data = {
    "user1": {
        "subName": "Netflix",
        "subDueDate": "2023-10-01",
        "subPayment": 49.99,
        "orderNo": "A0001",
        "orderStatus": "Delivered",
        "deliveryDate": "2023-09-25",
        "returnStatus": "Processed",
        "returnDueDate": "2023-09-30",
        "icStatus": "Active",
        "icStorage": "50GB",
        "aiStatus": "Verified",
        "aicontact": "user1@example.com",
        "aiBalance": 100.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 30.00,
        "deviceName": "iPhone 12",
        "faultStatus": "No issues",
        "fixMethod": "N/A",
        "storeName": "Apple Store - MixC, Shenzhen",
        "ATimeSlots": ["10:00AM-11:00AM", "03:00PM-04:00PM"],
        "acStatus": "Active",
        "acDueDate": "2024-10-01"
    },
    "user2": {
        "subName": "Amazon Prime",
        "subDueDate": "2023-11-15",
        "subPayment": 39.99,
        "orderNo": "B0002",
        "orderStatus": "Pending",
        "deliveryDate": "2023-11-10",
        "returnStatus": "Not Processed",
        "returnDueDate": "2023-11-20",
        "icStatus": "Active",
        "icStorage": "30GB",
        "aiStatus": "Verified",
        "aicontact": "user2@example.com",
        "aiBalance": 80.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 25.00,
        "deviceName": "Apple TV 4K",
        "faultStatus": "Hardware issue",
        "fixMethod": "Replacement",
        "storeName": "Apple Store - Union Square, San Francisc",
        "ATimeSlots": ["11:00AM-12:00PM", "04:00PM-05:00PM"],
        "acStatus": "Expired",
        "acDueDate": "2023-11-15"
    },
    "user3": {
        "subName": "Spotify",
        "subDueDate": "2023-12-05",
        "subPayment": 19.99,
        "orderNo": "C0003",
        "orderStatus": "Delivered",
        "deliveryDate": "2023-12-01",
        "returnStatus": "Processed",
        "returnDueDate": "2023-12-10",
        "icStatus": "Active",
        "icStorage": "10GB",
        "aiStatus": "Verified",
        "aicontact": "user3@example.com",
        "aiBalance": 50.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 15.00,
        "deviceName": "HomePod mini",
        "faultStatus": "No issues",
        "fixMethod": "N/A",
        "storeName": "Apple Store - Sydney, Australia",
        "ATimeSlots": ["01:00PM-02:00PM", "06:00PM-07:00PM"],
        "acStatus": "Active",
        "acDueDate": "2024-12-05"
    },
    "user4": {
        "subName": "Apple Music",
        "subDueDate": "2024-01-20",
        "subPayment": 59.99,
        "orderNo": "D0004",
        "orderStatus": "Processing",
        "deliveryDate": "2024-01-15",
        "returnStatus": "Pending",
        "returnDueDate": "2024-01-25",
        "icStatus": "Active",
        "icStorage": "40GB",
        "aiStatus": "Verified",
        "aicontact": "user4@example.com",
        "aiBalance": 90.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 35.00,
        "deviceName": "iPad mini (6th generation)",
        "faultStatus": "Minor issues",
        "fixMethod": "Software update",
        "storeName": "Apple Store - Orchard Road, Singapore",
        "ATimeSlots": ["09:00AM-10:00AM", "02:00PM-03:00PM"],
        "acStatus": "Expired",
        "acDueDate": "2023-01-20"
    },
    "user5": {
        "subName": "Hulu",
        "subDueDate": "2024-02-10",
        "subPayment": 69.99,
        "orderNo": "E0005",
        "orderStatus": "Delivered",
        "deliveryDate": "2024-02-05",
        "returnStatus": "Processed",
        "returnDueDate": "2024-02-10",
        "icStatus": "Active",
        "icStorage": "60GB",
        "aiStatus": "Verified",
        "aicontact": "user5@example.com",
        "aiBalance": 120.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 40.00,
        "deviceName": "iMac 24-inch (M3, 2023)",
        "faultStatus": "No issues",
        "fixMethod": "N/A",
        "storeName": "Apple Store - Dubai Mall, Dubai)",
        "ATimeSlots": ["10:00AM-11:00AM", "03:00PM-04:00PM"],
        "acStatus": "Active",
        "acDueDate": "2025-02-10"
    },
    "user6": {
        "subName": "Disney+",
        "subDueDate": "2024-03-15",
        "subPayment": 29.99,
        "orderNo": "F0006",
        "orderStatus": "Delivered",
        "deliveryDate": "2024-03-10",
        "returnStatus": "Processed",
        "returnDueDate": "2024-03-15",
        "icStatus": "Active",
        "icStorage": "20GB",
        "aiStatus": "Verified",
        "aicontact": "user6@example.com",
        "aiBalance": 70.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 20.00,
        "deviceName": "AirPods Pro",
        "faultStatus": "No issues",
        "fixMethod": "N/A",
        "storeName": "Apple Store - Sanlitun, Beijing",
        "ATimeSlots": ["11:00AM-12:00PM", "04:00PM-05:00PM"],
        "acStatus": "Active",
        "acDueDate": "2025-03-15"
    },
    "user7": {
        "subName": "Microsoft 365",
        "subDueDate": "2024-04-20",
        "subPayment": 49.99,
        "orderNo": "G0007",
        "orderStatus": "Pending",
        "deliveryDate": "2024-04-15",
        "returnStatus": "Not Processed",
        "returnDueDate": "2024-04-25",
        "icStatus": "Active",
        "icStorage": "50GB",
        "aiStatus": "Verified",
        "aicontact": "user7@example.com",
        "aiBalance": 100.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 30.00,
        "deviceName": "Apple Watch Series 7",
        "faultStatus": "Minor issues",
        "fixMethod": "Software update",
        "storeName": "Apple Store - IFC Mall, Chengdu",
        "ATimeSlots": ["09:00AM-10:00AM", "02:00PM-03:00PM"],
        "acStatus": "Active",
        "acDueDate": "2025-04-20"
    },
    "user8": {
        "subName": "Adobe Creative Cloud",
        "subDueDate": "2024-05-25",
        "subPayment": 59.99,
        "orderNo": "H0008",
        "orderStatus": "Processing",
        "deliveryDate": "2024-05-20",
        "returnStatus": "Pending",
        "returnDueDate": "2024-05-30",
        "icStatus": "Active",
        "icStorage": "40GB",
        "aiStatus": "Verified",
        "aicontact": "user8@example.com",
        "aiBalance": 90.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 35.00,
        "deviceName": "iPad Pro 12.9-inch (5th generation)",
        "faultStatus": "Hardware issue",
        "fixMethod": "Replacement",
        "storeName": "Apple Store - West Nanjing Road, Shanghai",
        "ATimeSlots": ["10:00AM-11:00AM", "03:00PM-04:00PM"],
        "acStatus": "Active",
        "acDueDate": "2025-05-25"
    },
    "user9": {
        "subName": "Dropbox",
        "subDueDate": "2024-06-30",
        "subPayment": 79.99,
        "orderNo": "I0009",
        "orderStatus": "Delivered",
        "deliveryDate": "2024-06-25",
        "returnStatus": "Processed",
        "returnDueDate": "2024-07-01",
        "icStatus": "Active",
        "icStorage": "70GB",
        "aiStatus": "Verified",
        "aicontact": "user9@example.com",
        "aiBalance": 150.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 50.00,
        "deviceName": "MacBook Air M1",
        "faultStatus": "No issues",
        "fixMethod": "N/A",
        "storeName": "Apple Store - Covent Garden, London",
        "ATimeSlots": ["11:00AM-12:00PM", "04:00PM-05:00PM"],
        "acStatus": "Expired",
        "acDueDate": "2022-06-30"
    },
    "user10": {
        "subName": "Google Workspace",
        "subDueDate": "2024-07-10",
        "subPayment": 89.99,
        "orderNo": "J0010",
        "orderStatus": "Delivered",
        "deliveryDate": "2024-07-05",
        "returnStatus": "Processed",
        "returnDueDate": "2024-07-10",
        "icStatus": "Active",
        "icStorage": "80GB",
        "aiStatus": "Verified",
        "aicontact": "user10@example.com",
        "aiBalance": 170.00,
        "apStatus": "Enabled",
        "tcStatus": "Active",
        "tcBalance": 60.00,
        "deviceName": "iPhone 13 Pro Max",
        "faultStatus": "No issues",
        "fixMethod": "N/A",
        "storeName": "Apple Store - Fifth Avenue, New York",
        "ATimeSlots": ["09:00AM-10:00AM", "02:00PM-03:00PM"],
        "acStatus": "Active",
        "acDueDate": "2025-07-10"
    }
}

# 将用户数据写入文件
with open('user_data.json', 'w') as file:
    json.dump(users_data, file, indent=4)
